name: Build App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Install Capacitor CLI globally
      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      # 5. Build web project
      - name: Build web project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}

      # 6. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # 7. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 7.1 Install Android SDK Platform 35 and Build Tools
      - name: Install Android 35 SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      # 8. Add Android platform (safe repeatable)
      - name: Add Android platform
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi

      # 9. Sync Capacitor plugins
      - name: Sync Capacitor
        run: npx cap sync android

      # 10. Fix Android Manifest (safe fallback)
      - name: Fix MainActivity name
        run: |
          if [ -f "android/app/src/main/AndroidManifest.xml" ]; then
            sed -i 's/android:name="MainActivity.kt"/android:name=".MainActivity"/' android/app/src/main/AndroidManifest.xml || true
            sed -i 's/android:name="MainActivity.java"/android:name=".MainActivity"/' android/app/src/main/AndroidManifest.xml || true
          fi

      # 11. Build the Android APK (debug to avoid signing issues)
      - name: Build Android APK
        run: cd android && ./gradlew assembleDebug --stacktrace --info

      # 12. Upload Web Build
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/

      # 13. Upload Android APK
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
